server:
  port: 8080
  servlet:
    context-path: /fuyingame
spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      file-size-threshold: 10MB

    thymeleaf:
      # 模板的模式，支持 HTML, XML TEXT JAVASCRIPT
      mode: HTML
      # 编码 可不用配置
      encoding: UTF-8
      # 内容类别,可不用配置
      servlet:
        content-type: text/html
      # 开发配置为false,避免修改模板还要重启服务器
      cache: false
      # 配置模板路径，默认是templates，可以不用配置
      prefix: classpath:/templates/

