spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/hmrzj
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validation-query: select 1 from dual
      test-on-borrow: true
      test-while-idle: true

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
#  redis:
#    host: 127.0.0.1
#    host: 10.13.1.172
#    port: 6379
#    password:
#    timeout: 10000
#    lettuce:
#      pool:
#        max-idle: 10
#        max-active: 10
#        min-idle: 5
#        max-wait: 10000
#    database: 0
swagger:
  enable: true
management:
  endpoints:
    web:
      exposure:
        include: beans,metrics,health
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.css.base.demo.dao: debug